name: Update Saved Tracks

#            ┌───────────── minute (0 - 59)
#            │ ┌───────────── hour (0 - 23)
#            │ │ ┌───────────── day of the month (1 - 31)
#            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#            │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#            │ │ │ │ │
#            │ │ │ │ │
#            │ │ │ │ │
#            * * * * *
on:
  schedule:
    - cron: "33 2 * * *" # Every day at 2:33am
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  PR_BOT_AUTHOR: quack-bot[bot] <98925477+quack-bot[bot]@users.noreply.github.com>

jobs:
  update-saved-tracks:
    name: Update Saved Tracks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Update Saved Tracks
        id: update_saved_tracks
        run: deno task update-saved-tracks
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        if: ${{ steps.update_saved_tracks.outputs.NEW_TRACKS_COUNT != 0 }}
        with:
          token: ${{ secrets.SPOTIFY_CR_PAT }}
          commit-message: |
            auto: [Spotify] - Update Saved Tracks
          committer: ${{ env.PR_BOT_AUTHOR }}
          author: ${{ env.PR_BOT_AUTHOR }}
          title: "[Spotify] - Update Saved Tracks"
          labels: "A:Auto Merge"
          branch: "new-tracks"
          branch-suffix: "short-commit-hash"
          delete-branch: true
          body: |
            Generated by `${{github.actor}}` via ${{github.sha}}
